name: Publish Artifacts

on:
  release:
    types:
      - published

jobs:
  Build_pre-1.17:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build -Dbuild16=true
      - name: Publish 1.14.4 - 1.16.5 Fabric
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          files-primary: fabric/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: fabric/build/libs/*-@(dev|sources|javadoc|shadow).jar
          loaders: |
            fabric
            quilt
          game-versions: |
            1.14.4
            1.15.0
            1.15.1
            1.15.2
            1.16.0
            1.16.1
            1.16.2
            1.16.3
            1.16.4
            1.16.5
          java: 8
          modrinth-featured: true
          modrinth-unfeature-mode: any
          version-type: beta
          version-resolver: releases
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip
      - name: Publish 1.14.4 - 1.16.5 Forge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          files-primary: forge/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: forge/build/libs/*-@(dev|sources|javadoc|shadow).jar
          loaders: forge
          game-versions: |
            1.14.4
            1.15.0
            1.15.1
            1.15.2
            1.16.0
            1.16.1
            1.16.2
            1.16.3
            1.16.4
            1.16.5
          java: 8
          modrinth-featured: true
          modrinth-unfeature-mode: any
          version-type: beta
          version-resolver: releases
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip
  Build_1.17+:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Publish 1.17+ Fabric
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          files-primary: fabric/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: fabric/build/libs/*-@(dev|sources|javadoc|shadow).jar
          loaders: |
            fabric
            quilt
          game-versions: |
            1.17.0
            1.17.1
            1.18.0
            1.18.1
            1.18.2
            1.19.0
            1.19.1
            1.19.2
            1.19.3
            1.19.4
          java: |
            8
            16
            17
          modrinth-featured: true
          modrinth-unfeature-mode: any
          version-type: beta
          version-resolver: releases
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip
      - name: Publish 1.17+ Forge
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          files-primary: forge/build/libs/!(*-@(dev|sources|javadoc|shadow)).jar
          files-secondary: forge/build/libs/*-@(dev|sources|javadoc|shadow).jar
          loaders: forge
          game-versions: |
            1.17.0
            1.17.1
            1.18.0
            1.18.1
            1.18.2
            1.19.0
            1.19.1
            1.19.2
            1.19.3
            1.19.4
          java: |
            8
            16
            17
          modrinth-featured: true
          modrinth-unfeature-mode: any
          version-type: beta
          version-resolver: releases
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip